using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace pluralsight.json.net.m3.d8
{
    [JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    public class AuthorJsonObjectOptIn
    {
        private string privateField;

        [JsonProperty]
        private string privateFieldWithAttribute;

        [JsonProperty]
        public string name { get; set; }

        public string[] courses { get; set; }

        public DateTime since;

        [NonSerialized]
        public bool happy;

        [JsonIgnoreAttribute]
        public object issues { get; set; }

        public Car car;

        private double salary { get; set; }

        private Car hobby { get; set; }
        private string NotAutoGeneratedProperty
        {
            get
            {
                return privateField;
            }
            set
            {
                privateField = value;
            }
        }
    }

    [JsonObject(MemberSerialization = MemberSerialization.OptOut)]
    public class AuthorJsonObjectOptOut
    {
        private string privateField;

        [JsonProperty]
        private string privateFieldWithAttribute;

        [JsonProperty]
        public string name { get; set; }

        public string[] courses { get; set; }

        public DateTime since;

        [NonSerialized]
        public bool happy;

        [JsonIgnoreAttribute]
        public object issues { get; set; }

        public Car car;

        private double salary { get; set; }

        private Car hobby { get; set; }

        private string NotAutoGeneratedProperty
        {
            get
            {
                return privateField;
            }
            set
            {
                privateField = value;
            }
        }
    }

    [JsonObject(MemberSerialization = MemberSerialization.Fields)]
    public class AuthorJsonObjectFields
    {
        private string privateField;

        [JsonProperty]
        private string privateFieldWithAttribute;

        [JsonProperty]
        public string name { get; set; }

        public string[] courses { get; set; }

        public DateTime since;

        [NonSerialized]
        public bool happy;

        [JsonIgnoreAttribute]
        public object issues { get; set; }

        public Car car;

        private double salary { get; set; }

        private Car hobby { get; set; }

        public string IsAutoGeneratedProp { get; set; }

        [JsonPropertyAttribute(DefaultValueHandling = DefaultValueHandling.Include)]
        public string NotAutoGenerated
        {
            get
            {
                return privateField;
            }
            set
            {
                privateField = value;
            }
        }

        public Relationship authorRelationship { get; set; }
    }
}

