using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace pluralsight.json.net.m3.d8
{
    public class JsonOptInOptOutDemo
    {
        public static void ShowJsonOptInOptOut()
        {
            Console.Clear();
            Console.WriteLine("*** Json OptIn & OptOut ***");

            Console.WriteLine("- OptIn");
            AuthorJsonObjectOptIn xavierAuthorOptIn = new AuthorJsonObjectOptIn()
            {
                name = "Xavier Morera",
                courses = new string[] { "Solr", "dotTrace", "Jira" },
                since = DateTime.Now
            };
            string xavierJsonOptIn = JsonConvert.SerializeObject(xavierAuthorOptIn, Formatting.Indented);
            Console.WriteLine(xavierJsonOptIn);

            Console.WriteLine("- OptOut");
            AuthorJsonObjectOptOut xavierAuthorOptOut = new AuthorJsonObjectOptOut()
            {
                name = "Xavier Morera",
                courses = new string[] { "Solr", "dotTrace", "Jira" },
                since = DateTime.Now
            };
            string xavierJsonOptOut = JsonConvert.SerializeObject(xavierAuthorOptOut, Formatting.Indented);
            Console.WriteLine(xavierJsonOptOut);

            Console.WriteLine("- Fields");
            AuthorJsonObjectFields xavierAuthorFields = new AuthorJsonObjectFields()
            {
                name = "Xavier Morera",
                courses = new string[] { "Solr", "dotTrace", "Jira" },
                since = DateTime.Now,
                IsAutoGeneratedProp = "Value for auto generated",
                NotAutoGenerated = "Value for NOT auto generated" //Not autogenerated fields are not included in serialization, only the private field
            };
            string xavierJsonFields = JsonConvert.SerializeObject(xavierAuthorFields, Formatting.Indented);
            Console.WriteLine(xavierJsonFields);
        }

    }
}
